# Habits {-}

habit, *n.* 1. a. Bodily apparel or attire; clothing,
raiment, dress. b. transf. and fig. Outward form or
appearance; guise. 2. spec. The dress of a religious
order; the habit, the monastic order or profession (cf.
‘the cowl’). 3. concr. The bodily ‘system’. 4. *Zool. and Bot.* 
The characteristic mode of growth and general
external appearance of an animal or plant. Hence
transf.; e.g. *in Cryst.* the characteristic mode of
formation of a crystal. 5. Habitation, abode. 6. A
tendency to act in a certain way, acquired by frequent
repetition of an act until it becomes almost involuntary.

## Harbor hidden {-}

*Harbor hidden in the middle of*

*a turbid current: sperm-tails flailing*

*radiant around a naked solus, ovum*

*beckoning its spent rays in.  Each*

*oval head (a match, a latent smoke of info)*

*rubs its cheek against the stony fruit…*


How does a life expand to meet capacity?

I splitting into Ys, diffuse, confused,

does one become, at last, a parody of self,

diminished twig clung stubborn to the branch’s

end?  or spread alive at once across its years, a

net of nerve to seize the wind in alleluia?


Impelled to fill one pattern once we start, the others,

never touched, lie fallow with imaginary crops—


Two trees grew separate in a garden once, but

how to tell the difference now? What life can we conceive

except the one we know, crooked with leaving?


Myopia, my opus: a cross-eyed squint

in radiating focus, half-divining vision.

*Deus absconditus* — draw in the periphery, grant me

direct sight, or at least a wending

life in which the distances are knit.

Even this flimsy string of time should be enough.


   *One matchhead breaks the skin and then, slow*
   
   *flame, the vast potentials end, begin.*

---

## Another day {-} 

Another day, the double-dozen heads it dregs aloft again,
nodding or shaking; candelabra which some vital wind,	 

obscured behind the quivered stacks of vision, whisper-flicks
this way or that, or else some other, as the chance elects.

Heavy with self, one glimpses mostly that.  What is of use?
Enlarge my empire, its flourished thoroughfares, loose	

runnels clogged sclerotic with expanding self.  Fill up these
days, this garbage heap of presents only half-received.

Abstraction is born on day’s conveyor-belt; repetitive stress
yawning out again its regimen of fractal chintz, except

that mind’s kaleidoscopic twists craft vistas, infinite,
hewn views from changeling oils: beaded, coursed and lit.

Each triggerhair of vision has its scope, a shrapnel
splash of filings chambered calm before the bang of APPLE,

EYE, and RAY: the bullet’s gaze honed down.  Any line
desires onely Everything; all squall & sprawl of motley time

oblonging darkly for a single prize—symmetrically to shut
up self in dim dimensioned squint—wanting to shunt

bright panoramas into cornices & hold them, ember
lit without a lick of motive.  Edges once limber end here;

end, that is, wherever here is scribed.  What’s actual is sketch; 
de-lineates itself: sight’s scrawl, a ghost of layered percepts.

Our eyes want grasp & thus a shape; their lids, euclidean, 
zodiac the bric-a-brac of bodies, sing—O fit me in,

empyrean, among your ferris-wheel of forms—dead center,
null hub pronouncing its confines as cause & answer.

Here are your parts, O hours, it indicates: a ramshackle Cast
extracted from my side: this meadow-choir, Grass-shafts,

a bending patch of cilia above/beneath the Hickory’s
dendritic click.  The mind as silt: black earth, black orrery—

Stone sockets pocked at lonely intervals throughout, an
interpolated blossom of reflections, foamy-crested Mountains

tippling up to Moon, that logical cloud around us curled.
Do we impose our visions on the world, or does the world

reveal us, gradually, as clustered portions of its patterning?
Either way, each solid sight is fraught with yearning,

graved in flaming, subtle lineaments.  My self & other
selves strung out, lined up, articulated like the sentence of

a stuttering deity: *“…I…I…I…I…,”* serrated cry
limned into type-cast characters that mar the music by

omitting difference.  No *I* is equal to another; each is
formed and forms within its singular address, reaches

through buoyant cell-skin &, nourished, becomes
alive again: volleyed between vacuum & continuum,

guessing which is home; gets dizzy on trajectories,
alights on breezes, blind to what their vector is.

In this same way I bore into the day, its billion limbs &
nodes: the host whose face I never wholly glimpse.

---

## Buttressed by the vasts {-}

Buttressed by  the vasts I *b*alance   somehow 

salient  The pinnacle & foc*u*s of   a visive arc 

Apex’s     lonesome    aper*t*ure   grips valleys’ 

blurry verdure       resolu*t*e    as single snow 

amid  abysm         whose f*r*ail hub cannot hold 

up   compass of      an Oth*e*r   without folding 

down      away     Mountain*s* in the        mind  

are movable    a billowing *s*fumato          Not 

actual     Not gridlock flu*e*ncy  of  prism-rock 

Out of chaos blossoms    Or*d*er       but out of 

many orders         Chaos       (the higher keys 

& grace-notes) a glissandi *b*ound   in  shimmer 

twixt strange strands     L*y*kesongs      among 

the archipelogos	       The universe’s flesh is 

holeless entire   yet yclep*t*e  by our invisions      

Divine defined     in     s*h*ards        Blindly 

Our   rank    divisions   c*e*nsered by   a scent 

of sweetnesse  as we travel   ever    in  between 

these   temples         Hea*v*en sees    the self 

strung from its fingers  Gr*a*vid   plumb    hung 

low    to dredge the  depth*s*          and gauge 

periphery of grace     A ca*t*enary      dreaming 

bulk    &    arc      of   *s*piring      gesture     

Praise  the strains    that   made me     Blesséd 

be our scattered   minds   *I*slands   The shores 

we pace      beside a great    &    solvent  body 

Oceanic flux of  axons    e*b*bing up the lengths 

ceived round us          Pe*a*ks   in its current 

pressed one to the next in *l*iquid  fissive kiss    

constrewing   sky in tesser*a*e        of mercury     

Your mercy built   deep  be*n*eath   sway of seas      

fluid Firm     a medium obs*c*uring distant sight 

with tangling task  of  mol*e*cules  in  colloquy 

forever   Where the whale        cathedral-ribbed 

floats in his own lost song*s*   An  entire  life 

returned   piecemeal  in  b*o*real strands   that 

reel the distances    rhyth*m*ing his body’s hull 

with thoughts forgot      R*e*turning    sonorous

as longing or   or as an un*h*eard prayer   bears  

its gigantic  answer hid am*o*ng the    serene  & 

severe expanse it treads   *w*ithout    a    word 

---

## Itinerant {-}

Itinerant, these threads appear amid the weave

this sturdy-seeming life affords; aureal strands

intervalled to salience from the drab; a dance

not understood by us, but done.  *Example*:  Leaves’

eternal shuttling between the branches & the worm;

renewed by death into the echelons, they return.


Ahistorical, we don’t notice the old currents’ return,

new as a day where antique generations weave

their hopeful accidents.  Nonetheless, we learn

to hang together.  Cords knit with many strands

hold tight, the ancients say and, if we try to leave,

entwine their arms in ours, inviting us to dance.


Sleuthing truths in books—the worn words dance

erratic in my eyes until the scales of sense return

to weigh proportions.  We forage in quarto leaves

hoping	for complex fruit among the rhythm’s weave

revealed, for lasting names to write upon the strands

Elsewhere, where seriphs hold the boundaries & burn.


All of our futures have been decided.  A heavy burin

draws the lines, & yet imbues them with that dance

suffusing any partial thing.  Fate, unfurling, strands

all of us in separate whorls, unable outward to return.

Perhaps my life’s isolated thread gleams in the weave.

Perhaps it doesn’t.  May I unstitch myself & leave?


Eventually every lovely thing must leave

aside what shapeliness our touchings can discern

—raw silk of skin beneath the starry weave—

and make its dwindling bed amid the garden’s danse

macabre.  My threadbare selvage even shall return

into new habits, knit from its own unraveled strands.


Day by layered day, I spin my crimson trail of strands

through citygrid, among the slowly coming leaves.

Here, steeped in the concrete, trampled days return

excavating me, leaving no scab unturned.	

We live in our own ruins, labyrinthine dances,

entering knots we pray we can unweave.


All that we’ve felt is a fray of fumbled strands

veering into textured dance.  The needle, hiding, leaves

ever to sojourn back behind the tapestry, and to return.


---

## T {-}


*To the Chief Singer;*
  *On My Stringed Instruments*


Through fire I choke to raise in song
   orisons from a burning crux;
Through smoke I aspire to sense, up
   helical stairways, firmer touch.

Earth’s heft I press against to leave
   constraints of weight below, &
   heave my thin soul heaven-ward
   into austerer circlings.

Earth’s heft I press against to leave
   fadeable impressions of my soul
   stamped here, on flesh, because
   I know no other place for love.

Nature embroiders with debris and
   graves our bloom with its undoing;
   entropic floræ of the spring cannot
   restring the nerves’ route to outpace
   our saving fears with gentlenesse.

Nature embroiders with debris in
   me, dissonating skin from thought,
   yet I must hold the loosenings 
   stringently, as in a crystal fugue,
   to resonate with your arrival.

Restring my mind: a web whose song
   I muffle, hungry, perched at center.
Nail our cords from agues to ægis: a
   green guitar to play the tensions out.

Except the grain delves into earth and 
   dies, it is itself—alone; but if it dies
   it brings forth unimaginable fruit.
Nail me through myself and into
   soil, changed.  	Selah.

Through vague meridians I must come,  
   restrung beyond poles of yes or no
   until my brittle, wandering will be 
   made into your music, sacrificed.

Except in others, I can never sing, so
   nail me to my enemy; his voice
   through my own lips articulating
   Selah.

---

## Suited {-}


*Simple and spiritual intentions slip easily from* 
*the memory unless joined to corporeal similitudes.*
    	—Jacobus Publicius, *Oratoriae artis epitome*, 1482



So slip into the patchwork cloak of day again,
into this rainbowed cowl: your Sunday best
made from the domed refraction of the rain.

Put on the miles your trepid feet will pass, laces
lagging forever behind them.  Ravel the streets,
each building’s sequent-chambered sweetnesses;
arrange these, room by room, in perfect circuitry:
neurons ensconcing a titanic, hybrid heart; its walls
dilating—halls, the treble valves & vaults that feed
souls’ tissue filtred out unto some deep deific Calm
peculiar to these thickets, pastel-clotted avenues
impastoed over all the distance fallen.

Review.  You are a mirror the world has raised up to
inspect itself.  A turbid vane of weather, ever
turning to rejoin its axis, ever seething through
until at last the pane can clasp both views together,
attenuated in this skein, where all the mottled 
landscapes vitrify: mind’s fragile cantilever.

Into the frayed array, then, into the bottle-
neck of stuff & senses, through razor-shoals,
through hills & veils, a panoply of puddles,					
each sky’s emulsion clinging to your shoe soles;
never to hold your gaze, its prospects blurring
through each others’ edges…you must go,
intent on one bright ending in a flurry
of endings bright with promise or disaster
nearing us now to quench our hurry.

So stand in your motions, fastened faster,
scuffing through the rut that clocktime blindly
leads you roundabout tomorrow into laughter.

Incise around your panoramic skull a skyline,
plucking the empty vault away: serene 
extract from traffic’s syllogistic whine.

Affix for your jawbone the mercurial sea, 
silences purling in its deeps—pure words
in between the surf’s clamoring teeth.

Let such shapes take you as the vivid earth
yields, offering your stillest interlude
fruit bittersweet as blood or music.  Let births
recur minutely as your limbs are pruned,
or else outgrow your scaffolding until—with rust,
mud, blossom, moss—the costumes swallow you.

Take as a spine the sunset’s incandescent isthmus,
hued by halflight & the sweet debris with which
each dusk has touched our tired cheeks & kissed us
momentarily before some sidereal switch, flipped,
eddies the sky’s exhausted lens to drift & dream 
myths strewn across the stars, reflected in a ditch.

Out of this, GOD authors psalms in periplum:
rhymes riven with the fear which limns all ritual, 
yearning its symmetries unto the farthest hem,
unto the squinting filigree of hope & pain, to cull
nutrition from the distances.  Spreading across
light years of dark material, his Soul
extends its green attention.  Out of the dust
swirled burning into personhood, he
singes songs where nothing true is lost.

Join with all nature, then, in manifolding 
opacity; its jumbled colors like a kind of night
I rifle through, yet have not found a hole in.

Now put on clouds of eyes.  Put on bright,
evaporated beads to magnify the sun’s secrets,
dredging up the torrents to arise as sight.

Try all of these: take, eat, taste, see.  Bliss 
orders the spheres; its starry pollen glistens,
ceilingless.  Aside those vasts, seek this
one face akin amid its difference,
refined by flickers, spectral grasps, & hold me
protean, until I shed all distance.

Out of me, pull what gleams; the rays unfolding
reflections from the waterdark, where sun extends,
evoking growth’s blush from the closed, cold deep.

Although we do not fit our habitat,	as when
liquid arcs to lens above a cup’s rim, still, we try.
So slip into the great restraints of day again,
into the means of meaning, fervent lines I
make from studying ecstasy; the bounding, bleary
image of your face, my changing child.

Let forms phantom through you.  Do not fear.
I rest beside you while the lullabies unwind,
touching my silent mouth to your whorled ear
until, hidden in your listening, you find
depths drawing up…thrum-thrum…a refrain					
echoing through ebbed flesh, keeping time,
slipping you into the bristly wave of day again…
