# Nimbuses {-}

## A {-}

And the lion will lie with the lamb
and the wolf lick the fur of the caribou, calmly,
and food chains cease their rattling,
all beastly tongues being salted with the taste of You,

at that time, fire engines shall careen
around the city just to feel the shrill
abundance of their wailing
and smile again, 
arriving always at 
another scene
aflame with blazons of Your Name

angels shall play
as anchormen and weatherwomen, grazing their hands
across the huge green screens of one
another’s bodies

and my prayers will be less and less like statements,
abandoning accusative, adverbial, and all 

alleluias stalled at
ahhh

as my desires reel their hooked lines in
at last, grinning at the lures’ bright emptiness
and watch each body swimming back
away into its depths, uncaught

as I bend down to pry
apart my rippling face, diving through
azure waterskin into

an ordinary room in which my wife
and children have composed 
 	actual life,
at home more than reflection’s
artificial heavens

all things shall be 
arranged in their usual places, but without 
atrophy of gesture
		         (a funnel as a trumpet
             a prayer rope as an abacus)
     
alive as eons, I will lie
awake as the benighted room
awaits each perfect second in suspense

and the cells will be opened 
and I will enter their gates with thanksgiving 



---

## B {-}


---

## C {-}


---
## D {-}


---
## E {-}

“Retell legends,” ebb the embers .
  Ye, edgeless Essence
beget the depthless present tense.

Excerpted newsreel feeds: Eve errs, 
   etc… Serpent repents.
The expected sentence reversed. 

Hellbent, resplendent, we veer between
   extremes⇀never rested,
we seek new selves.  Keened.

There there, levees; strewn perplexed
  where shelter seeps.
Where tempest extends, recedes, recedes.

Elements render them defenseless:  speech
   freezes, nerves tremble,   
vessels wreck.  Flesh bleeds elements.

Speech fetters, verse tethers, yet
  we seek Thee
trenched there, seeded between letters.

Ye rest, pretend, engender spheres,
  bejewel deserts, beget
the breeze-sketched trees.  Preserve them.

We beseech Thee, Nether-Nested:
  dwell deep  here
delve green between the temples
	
Be present.  Be here.  Be
  dented where we
met.  Be felt there yet.


---
## F {-}

---
## G {-}

Gorged by grace, I gurgle supplications.

Give me etcetera.  Give me patience.
Give me the holy ghosts I have resigned,
gathering facts to fill my growling mind.

Gaze me naked.  Let me become
gourmand of groin and gristle.  Let my tongue
graze daily sweat from love’s gooseflesh; 
glutted with hunger nonetheless.

God, nothing gives me pause; not
gulps of cigarette, not shopping malls, not
gospel truth, not pain.

Grease the clock’s gears, rewind again:
grow me a garden where all things recede, my own
globed ripeness turning
gaunt with want.

Gird me with distance, a pen to grave these fevered
glyphs on garlic paper, gilt with the pungent
gift it guards yet cannot ever grasp.

God of the gaps, You peel my meanings back.


---
## H {-}

---
## I {-}

---
## J {-}

---
## K {-}

---
## L {-}

---
## M {-}

---
## N {-}

---
## O {-}

---
## P {-}

---
## Q {-}

---
## R {-}

---
## S {-}

---
## T {-}

---
## U {-}

---
## V {-}

---
## W {-}

What do you want with me?
Why give me a mind, a welter of
wings that beat each other
weak with wanderlust?

When I was young, I fashioned sprawling
walls with Legos.  Nostalgia, meanwhile,
wrapt me in its bounds.  I waited for the losses
waiting would create.

Why waken those wondrous
worlds in me, only to wag Your finger
warning: “Watch and wait” 
while hope wrings wrinkles in my face?

What good’s my wondering now?
WHERE  WHEN  WHO  HOW  WHY
WHAT: a compass rose 
whithering at the window ledge.

With my bow and my quiver I aim at You.

Words, these words, are a wilderness of want
where I am blown toward some vanishing point
without ever arriving; where Your heady weather
wields me, whittled whole.

While thoughts quake my body’s scaffolding,
worlds go on—snow thaws,
weeds squeeze through, flowers hoist their sweetness up
without knowing how.

We writhe in one another’s waves;
whorled in their turbulence, cleansed.  The Question
washed within the never of its quest.  The Answer
widening its wake till waning

water cannot bear its trace: wending on, inspired
with wind the Question makes.


---
## X {-}

---
## Y {-}

---
## Z {-}

---
## ○ {-}

*“‘...ma tu perche vai?’… ‘per tornar altra volta*
*la dov’io son, fo io questo vïaggio”* 	(Purgatorio 2.90)  
[“Why are you on this way?  So that I may return where I am.”]

My soul has leeched into my skin.
Raw, haunted.  Prayers are like this, a cloud
of breath on an icon's varnish.

On a good day, my thoughts rest
on the grass like the shadows of grass,
blade by blade by blade.

I am trying to understand — in 
the most basic sense: to be beneath, perhaps,
or even to be with

To run a hand along the branching
walls of ancient cities
as a way to know that I am

To mouth, like wind across 
doorways, voluble syllables

Not to be bewitched by thoughts

To handle stones: earth’s braille 
that scrapes my fingerprints,
swallows touch into rough sense

In an image blacked by candle
smoke, You press one 
finger to another finger.

Some nights the child me would pinch
another smaller me, another room,
and so on: symbols pressed breathless.

The storied worlds have looked their sights 
away.  The only faith I still attempt —

Finger pointing to finger.
The touch of something touched 
touching back.

Bless.
