# (PART) Overtake the Creases {-}

# Overtake

## Obsolescence



---

## Versions



---

## Event Planning




---

## Replace



---

## Taxonomy



## Accrual


# The Light Reactions | The Dark Reactions


# Creases

## Autumn

Novemberous, the body a warm sliver
in frigid field, stark letter 
on page.

Amid the panoplied 
cicatrice of branches, splay
of angles swim in flame, in spectrum-
petalled autumn: somewhere in
there, the dirt is firm as death
and resurrection, shared
marginalia of earth & air, & we
are scenery the gorgeous forest stares.

Lean down & whisper histories
in the upturned ears of flowers.
Go in.  Tug up
the scurf.  Lay theorems,
accountings, poems 
there in the hungry nave.

Aloft, gold flecks
of light revolving float
down & up, alight
upon pond, unlock
& lock
	as tesserae, leaf’s toothy 
algorithmic edge, as form 
which is proportion which is always 
almost breaking 

as the great lake: its
coruscant facets
            etched everyhere

St. Gregory describes us rising, sleuthing
remnant atoms across 
the universe, the pulse of self still resonant

Not atom but PERSON is the fundamental thing.
Not space but RELATION. 

I want to be simple
as sand,
 as years between sands

as pattern which is ratio which is word which is wilderness which is sacrifice which is love

If the doors of perception were cleansed
If the dark matter were swept away
If 90% of the body’s cells are not human 

then what is it that prays in us?
then stars would fill the spaceless sky 
then we would see things as they are.

## Winter


## Spring


## Latesummer


With our last polaroids we took pictures of LIGHT and DARKNESS

Wild children ranged through the breezy doors

Scenes wandered through us
unfinished, smudged with cirrus
moon hovered over sunred trees

Most of matter is empty space.
Most of what I know is ignorance.

Dear one, you open in flickers.
How can I keep you 
from closing up? 
from hardening 
around your guesses?

A person doesn’t change
except within boundaries
as crystals sharpen in the dank dark
as wildflowers crowd the trails edge

A membrane is prerequisite for LIFE.
There has to be an inside and an out.
What ratio of fear to reckless love?
Strong but not brittle, open not spilling.
How do we change without unravelling?

Dear one, 
hold on—
a little threadsong
   to carry you
through deep woods

We are animals hunting for meanings, wearing
the pelts of meanings.

Nor is there singing school but studying:
tibia,  fabula,  nebula

vastuary

All summer I have been reading you stories when I should have been teaching 
you silence

using words made 
of beach stones
                            —the round 
tongues of eons

All bloom long
I should have been learning subtraction.

It is natural to lie down.
To pack my mouth full.

O coax fruit from my lips, O blank O
harbinger O time
O darling girl
I’m gonna hold you in my arms 
til your feet grow down




